services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app:latest
    container_name: application
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"            # PHP-FPM port
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"              # browse on http://localhost:8080
    volumes:
      - ./:/var/www/html:ro    # your code, read-only
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      
  node:
    image: node:18-alpine
    container_name: node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: >
      sh -c "
        npm install -g pnpm &&
        pnpm install &&
        pnpm dev -- --host=0.0.0.0
      "
    ports:
      - "5173:5173"
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
